### ISSUE TITLE
Library does not compile on Arduino Nano 33 BLE

### ISSUE THREAD

**Issue by sabin-roman** [dmadison/ServoInput#17]
Hi David, the library works great on Uno & Mega, however, it does not compile on Arduino Nano 33 BLE. 

I saw there are a few other folks that left comments on forums about this issue, so I guess more people could find this useful. 

Hope you have some time to address it.

**Comment by dmadison** [comment]
Hi Sabin, thanks for creating this issue. I've pushed some changes to the `universal` branch which should let the library work on the Nano 33. Please give it a try and let me know if there are any problems.

**Comment by dmadison** [comment]
Fixed in #18. Feel free to re-open if there's an issue.
