### ISSUE TITLE
Add support STM32F401

### ISSUE THREAD

**Issue by megom1975** [dmadison/ServoInput#25]
The library is very good. Thank you. Can you add support for STM32F103, STM32F401?

**Comment by dmadison** [comment]
Hello. Have you tested the library with those boards? It appears that both are supported by [the Arduino STM32 Core](https://github.com/stm32duino/Arduino_Core_STM32).

I'd be happy to look into any compatibility problems that you run into. Feel free to reopen this issue with more information.
